import React from 'react';
import { AbsoluteFill, Audio, Series, staticFile, useCurrentFrame } from 'remotion';
import { ensureFonts } from './lib/fonts';
import timeline from './timeline.json';
import { win } from './lib/math';
import { AUTUMN_SEC, Autumn, SPRING_SEC, SUMMER_SEC, Spring, Summer, WINTER_SEC, Winter } from './scenes/Childhood';
import { PARTING_SEC, Parting } from './scenes/Parting';
import { DROUGHT_SEC, Drought, EPILOGUE_SEC, Epilogue, REUNION_SEC, Reunion } from './scenes/Return';
import { CREDITS_SEC, Credits, TITLE_SEC, Title } from './scenes/Titles';
import { COURTSHIP_SEC, Courtship, FATHERHOOD_SEC, Fatherhood, OLD_AGE_SEC, OldAge, YOUTH_SEC, Youth } from './scenes/Years';

ensureFonts();

export const FPS = timeline.fps;
export const PAPER = '#efe3c8';

interface Scene {
  id: string;
  sec: number;
  C: React.FC;
  /** Dip-to-paper durations, seconds. */
  fadeIn: number;
  fadeOut: number;
}

export const SCENES: Scene[] = [
  { id: 'title', sec: TITLE_SEC, C: Title, fadeIn: 0.8, fadeOut: 1.4 },
  { id: 'parting', sec: PARTING_SEC, C: Parting, fadeIn: 2, fadeOut: 2.5 },
  { id: 'spring', sec: SPRING_SEC, C: Spring, fadeIn: 1.2, fadeOut: 1.2 },
  { id: 'summer', sec: SUMMER_SEC, C: Summer, fadeIn: 1.2, fadeOut: 1.2 },
  { id: 'autumn', sec: AUTUMN_SEC, C: Autumn, fadeIn: 1.2, fadeOut: 1.2 },
  { id: 'winter', sec: WINTER_SEC, C: Winter, fadeIn: 1.2, fadeOut: 1.6 },
  { id: 'youth', sec: YOUTH_SEC, C: Youth, fadeIn: 1.4, fadeOut: 1.2 },
  { id: 'courtship', sec: COURTSHIP_SEC, C: Courtship, fadeIn: 1.2, fadeOut: 1.2 },
  { id: 'fatherhood', sec: FATHERHOOD_SEC, C: Fatherhood, fadeIn: 1.2, fadeOut: 1.4 },
  { id: 'oldAge', sec: OLD_AGE_SEC, C: OldAge, fadeIn: 1.4, fadeOut: 2 },
  { id: 'drought', sec: DROUGHT_SEC, C: Drought, fadeIn: 1.6, fadeOut: 0 },
  { id: 'reunion', sec: REUNION_SEC, C: Reunion, fadeIn: 0, fadeOut: 2.2 },
  { id: 'epilogue', sec: EPILOGUE_SEC, C: Epilogue, fadeIn: 2.5, fadeOut: 3 },
  { id: 'credits', sec: CREDITS_SEC, C: Credits, fadeIn: 1, fadeOut: 2.2 },
];

export const sceneFrames = (s: Scene) => Math.round(s.sec * FPS);

/** First frame of a scene, for tests and the score. */
export const sceneStart = (id: string) => {
  let f = 0;
  for (const s of SCENES) {
    if (s.id === id) return f;
    f += sceneFrames(s);
  }
  return f;
};

export const TOTAL_FRAMES = SCENES.reduce((n, s) => n + sceneFrames(s), 0);

const Dip: React.FC<{ sec: number; fadeIn: number; fadeOut: number }> = ({ sec, fadeIn, fadeOut }) => {
  const t = useCurrentFrame() / FPS;
  const a = Math.max(fadeIn > 0 ? 1 - win(t, 0, fadeIn) : 0, fadeOut > 0 ? win(t, sec - fadeOut, sec) : 0);
  if (a <= 0.001) return null;
  return <AbsoluteFill style={{ backgroundColor: PAPER, opacity: a }} />;
};

/** Generated by scripts/father-and-son-score.mjs from the same timeline. */
export const SCORE = 'father-and-son/score.mp3';

export const FatherAndSon: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: PAPER }}>
    <Audio src={staticFile(SCORE)} />
    <Series>
      {SCENES.map((s) => (
        <Series.Sequence key={s.id} durationInFrames={sceneFrames(s)} name={s.id}>
          <s.C />
          <Dip sec={s.sec} fadeIn={s.fadeIn} fadeOut={s.fadeOut} />
        </Series.Sequence>
      ))}
    </Series>
  </AbsoluteFill>
);
