#!/usr/bin/env python3
"""
Bakes the few strings "Father and Son" sets in type into SVG glyph outlines, so the film
never waits on a web font while rendering.

  pip install fonttools
  python3 scripts/father-and-son-glyphs.py MaShanZheng-Regular.ttf "CormorantGaramond[wght].ttf"

Fonts: Ma Shan Zheng and Cormorant Garamond from github.com/google/fonts (SIL OFL 1.1).
Writes src/films/father-and-son/fonts/glyphs.ts — 1 em = 1000 units, y pointing down.
"""
import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

BRUSH_TEXT = "父与子清明夏至秋分大雪立小暑寒露霜降大寒春向致敬念《》"
SERIF_TEXT = "".join(chr(c) for c in range(0x20, 0x7F)) + "ë–·’"


def bake(font: TTFont, chars: str) -> dict:
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    upm = font["head"].unitsPerEm
    s = 1000 / upm
    out = {}
    for ch in chars:
        name = cmap.get(ord(ch))
        if name is None:
            raise SystemExit(f"missing glyph for {ch!r}")
        pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.0f}")
        glyphs[name].draw(TransformPen(pen, (s, 0, 0, -s, 0, 0)))
        out[ch] = (pen.getCommands(), round(font["hmtx"][name][0] * s))
    return out


def ts_table(name: str, table: dict) -> str:
    rows = []
    for ch, (d, adv) in table.items():
        key = ch.replace("\\", "\\\\").replace("'", "\\'")
        rows.append(f"  '{key}': ['{d}', {adv}],")
    return f"export const {name}: Record<string, [string, number]> = {{\n" + "\n".join(rows) + "\n};\n"


def main() -> None:
    brush_path, serif_path = sys.argv[1], sys.argv[2]
    brush = TTFont(brush_path)
    serif = TTFont(serif_path)
    if "fvar" in serif:
        serif = instantiateVariableFont(serif, {"wght": 500})
    root = Path(__file__).resolve().parent.parent
    target = root / "src/films/father-and-son/fonts/glyphs.ts"
    target.write_text(
        "// Generated by scripts/father-and-son-glyphs.py — glyph outlines of Ma Shan Zheng and\n"
        "// Cormorant Garamond (SIL OFL 1.1, licences beside this file). [path, advance], 1 em = 1000.\n\n"
        + ts_table("BRUSH_GLYPHS", bake(brush, BRUSH_TEXT))
        + "\n"
        + ts_table("SERIF_GLYPHS", bake(serif, SERIF_TEXT)),
        encoding="utf-8",
    )
    print(f"wrote {target.relative_to(root)} ({target.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
